# Example use matrix multiplication in nets with three layers

In [13]:
import numpy as np

In [14]:
#input signal 
I = np.array([[0.9], [0.1], [0.8]], dtype="float")


In [15]:
I

array([[ 0.9],
       [ 0.1],
       [ 0.8]])

In [16]:
# weight matrix from input to hidden
W_input_to_hidden = np.array(([0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]), dtype="float")

In [17]:
W_input_to_hidden

array([[ 0.9,  0.3,  0.4],
       [ 0.2,  0.8,  0.2],
       [ 0.1,  0.5,  0.6]])

In [18]:
X_hidden = np.dot(W,I)

In [33]:
print(X_hidden)

[[ 1.16]
 [ 0.42]
 [ 0.62]]


In [43]:
#применяем функцию активации(сигмоиду)
O_hidden = [(lambda x : 1.0/(1.0+2.7182818284590452353602874713527**x))(x) for x in X_hidden]

In [44]:
print(O_hidden)

[array([ 0.23866729]), array([ 0.39651675]), array([ 0.34978145])]


In [46]:
W_hidden_to_output = np.array(([0.3, 0.7, 0.5], [0.6, 0.5, 0.2], [0.8, 0.1, 0.9]))

In [47]:
W_hidden_to_output


array([[ 0.3,  0.7,  0.5],
       [ 0.6,  0.5,  0.2],
       [ 0.8,  0.1,  0.9]])

In [49]:
X_output = np.dot(W_hidden_to_output, O_hidden)

In [50]:
X_output

array([[ 0.52405264],
       [ 0.41141504],
       [ 0.54538881]])

In [52]:
O_output = [(lambda x : 1.0/(1.0+2.7182818284590452353602874713527**x))(x) for x in X_output]

In [53]:
O_output

[array([ 0.37190508]), array([ 0.39857287]), array([ 0.3669349])]